import * as THREE from'three';
import portrait from './portrait.js';
export const types=['blocks','pipes','valves','circuit','jigsaw','pressure','symbols','frequency','keypad','escape'];
export function bindPuzzles({getRoom,onSolved,canOpen}){
 const modal=document.getElementById('modal'),game=document.getElementById('game'),status=document.getElementById('status'),title=document.getElementById('pTitle'),desc=document.getElementById('pDesc');
 let solved=Array(10).fill(false),clean3D=()=>{};
 const lamp=document.createElement('div');lamp.id='doorStateLamp';lamp.innerHTML='<span></span>';document.body.appendChild(lamp);
 const syncLamp=()=>{const ok=solved[getRoom()];lamp.className=ok?'green':'red';lamp.title=ok?'الباب مفتوح':'الباب مقفل'};
 new MutationObserver(syncLamp).observe(document.getElementById('roomSub'),{childList:true,subtree:true});syncLamp();
 const showEnding=()=>{let e=document.getElementById('ending');if(!e){e=document.createElement('div');e.id='ending';Object.assign(e.style,{position:'fixed',inset:'0',zIndex:'100',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',textAlign:'center',background:'linear-gradient(#8bb8d6,#e8d6ae)',color:'#182027',fontFamily:'system-ui',padding:'24px'});e.innerHTML='<div style="font-size:clamp(30px,7vw,64px);font-weight:900">تم الخروج من العزل</div><div style="font-size:clamp(16px,3vw,26px);margin-top:12px">فتحت بوابة السطح وخرجت من الملجأ بنجاح.</div><button id=restartGame style="margin-top:28px;padding:12px 20px;border:0;border-radius:10px;font-weight:800">إعادة اللعب</button>';document.body.appendChild(e);document.getElementById('restartGame').onclick=()=>location.reload()}e.style.display='flex'};const complete=()=>{const r=getRoom();if(solved[r])return;solved[r]=true;syncLamp();status.textContent=r===9?'تم فتح بوابة السطح':'تم الحل — الباب مفتوح';status.className='status solved';onSolved(r,true);setTimeout(()=>{clean3D();modal.classList.remove('show');if(r<9)document.getElementById('next')?.click();else showEnding()},850)};
 function stage(build,onPick){clean3D();game.innerHTML='<div class="p3d"><canvas id="p3canvas"></canvas></div>';const canvas=document.getElementById('p3canvas'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(360,330,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,360/330,.1,50);camera.position.set(0,0,9);scene.add(new THREE.HemisphereLight(0xffffff,0x20242a,1.5));const l=new THREE.DirectionalLight(0xffffff,2.2);l.position.set(3,5,6);scene.add(l);const hits=[];build(scene,hits);const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();const pick=e=>{const r=canvas.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const h=ray.intersectObjects(hits,true)[0];if(h){let o=h.object;while(o.parent&&o.userData.idx===undefined)o=o.parent;if(o.userData.idx!==undefined)onPick(o.userData.idx,o)}};canvas.addEventListener('pointerdown',pick);let live=true;function anim(){if(!live)return;requestAnimationFrame(anim);renderer.render(scene,camera)}anim();clean3D=()=>{live=false;canvas.removeEventListener('pointerdown',pick);renderer.dispose()};return{scene,hits}}
 const metal=()=>new THREE.MeshStandardMaterial({color:0x626a70,metalness:.7,roughness:.28}),dark=()=>new THREE.MeshStandardMaterial({color:0x24272b,metalness:.45,roughness:.42});
 function numMat(n,sel=false){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle=sel?'#8a5a22':'#343a40';x.fillRect(0,0,256,256);x.fillStyle='#fff';x.font='bold 120px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(n,128,138);const t=new THREE.CanvasTexture(c);return new THREE.MeshStandardMaterial({map:t,metalness:.25,roughness:.45})}
 function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
 function blocks(){let a=shuffle([1,2,3,4,5,6,7,8,9]),sel=-1;const draw=()=>stage((s,h)=>{a.forEach((v,i)=>{const x=(i%3-1)*2,y=(1-Math.floor(i/3))*2;const m=new THREE.Mesh(new THREE.BoxGeometry(1.55,1.55,.7),numMat(v,i===sel));m.position.set(x,y,0);m.rotation.x=-.12;m.userData.idx=i;s.add(m);h.push(m)})},i=>{if(sel<0)sel=i;else if(sel===i)sel=-1;else{[a[sel],a[i]]=[a[i],a[sel]];sel=-1;if(a.every((v,j)=>v===j+1)){complete();return}}draw()});draw()}
 function pipeModel(i,rot){const g=new THREE.Group();g.userData.idx=i;const matp=new THREE.MeshStandardMaterial({color:0x4d8ba5,metalness:.65,roughness:.25});const tube=(x,y,len,rz)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(.22,.22,len,18),matp);m.position.set(x,y,0);m.rotation.z=rz;m.userData.idx=i;g.add(m)};if(i%2){tube(.45,0,.9,Math.PI/2);tube(0,.45,.9,0);const e=new THREE.Mesh(new THREE.SphereGeometry(.24,16,12),matp);e.userData.idx=i;g.add(e)}else tube(0,0,1.7,Math.PI/2);g.rotation.z=rot*Math.PI/2;return g}
 function pipes(){let r=[0,1,3,2,1,0,2,3,0];const target=j=>j%3===1?1:0;const draw=()=>stage((s,h)=>{r.forEach((v,i)=>{const x=(i%3-1)*2.15,y=(1-Math.floor(i/3))*2.05;const pad=new THREE.Mesh(new THREE.BoxGeometry(1.8,1.65,.25),dark());pad.position.set(x,y,-.25);s.add(pad);const g=pipeModel(i,v);g.position.set(x,y,0);s.add(g);g.traverse(o=>{if(o.isMesh)h.push(o)})})},i=>{r[i]=(r[i]+1)%4;if(r.every((x,j)=>x===target(j))){complete();return}draw()});draw()}
 function valves(){let a=[0,0,0],target=[2,1,3];const draw=()=>stage((s,h)=>{a.forEach((v,i)=>{const g=new THREE.Group();g.userData.idx=i;g.position.x=(i-1)*2.5;g.rotation.z=v*Math.PI/2;const ring=new THREE.Mesh(new THREE.TorusGeometry(.75,.14,16,36),new THREE.MeshStandardMaterial({color:0xb34235,metalness:.6,roughness:.3}));ring.userData.idx=i;g.add(ring);for(let k=0;k<4;k++){const sp=new THREE.Mesh(new THREE.BoxGeometry(1.25,.11,.12),metal());sp.rotation.z=k*Math.PI/2;sp.userData.idx=i;g.add(sp)}const marker=new THREE.Mesh(new THREE.SphereGeometry(.16,16,12),new THREE.MeshStandardMaterial({color:0xffd447,emissive:0x8a5c00,emissiveIntensity:2.5}));marker.position.set(0,.72,.16);marker.userData.idx=i;g.add(marker);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,.25,18),metal());hub.rotation.x=Math.PI/2;hub.userData.idx=i;g.add(hub);s.add(g);g.traverse(o=>{if(o.isMesh)h.push(o)})})},i=>{a[i]=(a[i]+1)%4;status.textContent='الصمام '+(i+1)+': '+a[i]+'/4';status.className='status';if(a.every((x,j)=>x===target[j])){complete();return}draw()});draw()}
 function circuit(){let a=[0,0,0,0],target=getRoom()===7?[1,0,1,1]:[1,1,0,1];const draw=()=>stage((s,h)=>{a.forEach((v,i)=>{const g=new THREE.Group();g.userData.idx=i;g.position.x=(i-1.5)*1.8;const base=new THREE.Mesh(new THREE.BoxGeometry(1.2,2,.5),dark());base.userData.idx=i;g.add(base);const lever=new THREE.Mesh(new THREE.BoxGeometry(.3,1.3,.3),new THREE.MeshStandardMaterial({color:v?0x45b86a:0xb84c42,metalness:.5,roughness:.32}));lever.position.y=v?.35:-.35;lever.rotation.z=v?-.55:.55;lever.userData.idx=i;g.add(lever);const bulb=new THREE.Mesh(new THREE.SphereGeometry(.23,18,12),new THREE.MeshStandardMaterial({color:v?0x55ff88:0xff554d,emissive:v?0x33cc66:0xcc332d,emissiveIntensity:4}));bulb.position.set(0,.78,.34);bulb.userData.idx=i;g.add(bulb);const halo=new THREE.Mesh(new THREE.TorusGeometry(.3,.045,10,24),new THREE.MeshBasicMaterial({color:v?0x8cffaa:0xff7777}));halo.position.set(0,.78,.32);halo.userData.idx=i;g.add(halo);const hitbox=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.8,.65),new THREE.MeshBasicMaterial({transparent:true,opacity:.001,depthWrite:false}));hitbox.position.z=.18;hitbox.userData.idx=i;g.add(hitbox);s.add(g);g.traverse(o=>{if(o.isMesh)h.push(o)})})},i=>{a[i]^=1;status.textContent='المفتاح '+(i+1)+': '+(a[i]?'تشغيل':'إيقاف');status.className='status';if(a.every((x,j)=>x===target[j])){complete();return}draw()});draw()}

 function pressure(){let a=[0,0,0],target=[2,0,1];const draw=()=>stage((s,h)=>{a.forEach((v,i)=>{const g=new THREE.Group();g.userData.idx=i;g.position.x=(i-1)*2.3;const base=new THREE.Mesh(new THREE.BoxGeometry(1.2,2.6,.45),dark());base.userData.idx=i;g.add(base);const fill=new THREE.Mesh(new THREE.BoxGeometry(.55,.55+.55*v,.18),new THREE.MeshStandardMaterial({color:[0x4c85a6,0xf0b54a,0xff5b4f][v],emissive:[0x18364a,0x5c3a00,0x651a12][v],emissiveIntensity:1.8}));fill.position.y=-.7+(.55+.55*v)/2;fill.userData.idx=i;g.add(fill);const lamp2=new THREE.Mesh(new THREE.SphereGeometry(.16,14,10),new THREE.MeshStandardMaterial({color:v===target[i]?0x49ff72:0xff4b43,emissive:v===target[i]?0x1cae45:0x8c1510,emissiveIntensity:3}));lamp2.position.y=1;lamp2.userData.idx=i;g.add(lamp2);s.add(g);g.traverse(o=>{if(o.isMesh)h.push(o)})})},i=>{a[i]=(a[i]+1)%3;status.textContent='ضغط '+(i+1)+': '+a[i]+'/2';if(a.every((x,j)=>x===target[j])){complete();return}draw()});draw()}
 function symbols(){let step=0,seq=[2,0,3,1],cols=[0x55c7ff,0xffcf55,0xff6b6b,0x7be37b];const draw=()=>stage((s,h)=>{for(let i=0;i<4;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(1.35,1.35,.45),new THREE.MeshStandardMaterial({color:cols[i],emissive:step>0&&seq[step-1]===i?cols[i]:0x000000,emissiveIntensity:1.4,metalness:.2,roughness:.45}));m.position.x=(i-1.5)*1.75;m.userData.idx=i;s.add(m);h.push(m)}},i=>{if(i===seq[step]){step++;status.textContent='تسلسل الرموز: '+step+'/4';if(step===seq.length){complete();return}}else{step=0;status.textContent='تسلسل خاطئ — ابدأ من جديد'}draw()});draw()}
 function frequency(){let a=[0,0,0],target=[3,1,4];const draw=()=>stage((s,h)=>{a.forEach((v,i)=>{const g=new THREE.Group();g.userData.idx=i;g.position.x=(i-1)*2.3;const dial=new THREE.Mesh(new THREE.CylinderGeometry(.72,.72,.28,28),metal());dial.rotation.x=Math.PI/2;dial.userData.idx=i;g.add(dial);const needle=new THREE.Mesh(new THREE.BoxGeometry(.12,.85,.16),new THREE.MeshStandardMaterial({color:0xffd257,emissive:0x6a4500,emissiveIntensity:2}));needle.position.y=.28;needle.rotation.z=(v-2)*.55;needle.userData.idx=i;g.add(needle);s.add(g);g.traverse(o=>{if(o.isMesh)h.push(o)})})},i=>{a[i]=(a[i]+1)%5;status.textContent='التردد '+(i+1)+': '+a[i]+'/4';if(a.every((x,j)=>x===target[j])){complete();return}draw()});draw()}
 function keypad(){clean3D();let code='',target='7314';game.innerHTML='<div id=kp style="display:grid;grid-template-columns:repeat(3,76px);gap:8px;justify-content:center"></div><div id=kpOut style="text-align:center;font-size:26px;letter-spacing:8px;margin-top:14px">----</div>';const k=document.getElementById('kp'),out=document.getElementById('kpOut');[1,2,3,4,5,6,7,8,9,0].forEach(n=>{const b=document.createElement('button');b.textContent=n;b.style.cssText='height:64px;border-radius:10px;border:1px solid #ffffff33;background:#2b3035;color:white;font-size:24px;font-weight:800';b.onclick=()=>{code=(code+String(n)).slice(-4);out.textContent=code.padEnd(4,'-');if(code.length===4){if(code===target){complete()}else{status.textContent='رمز خاطئ';code='';setTimeout(()=>out.textContent='----',250)}}};k.appendChild(b)})}
 function escapePuzzle(){clean3D();let step=0;const labels=['تشغيل طاقة المصعد','فتح قفل الأمان','فتح بوابة السطح'];game.innerHTML='<div id=esc style="display:flex;flex-direction:column;gap:12px;max-width:340px;margin:auto"></div>';const e=document.getElementById('esc');labels.forEach((t,i)=>{const b=document.createElement('button');b.textContent=(i+1)+' · '+t;b.style.cssText='padding:18px;border-radius:12px;border:1px solid #ffffff33;background:#30363b;color:white;font-size:17px;font-weight:800';b.onclick=()=>{if(i===step){b.style.background='#24763d';b.disabled=true;step++;status.textContent='إجراء الخروج '+step+'/3';if(step===3)complete()}else status.textContent='نفّذ خطوات الخروج بالترتيب'};e.appendChild(b)})}

 function jigsaw(){clean3D();let a=shuffle([0,1,2,3,4,5,6,7,8]),sel=-1;game.innerHTML='<div class="jig" id="j" dir="ltr"></div>';const j=document.getElementById('j');const ok=()=>a.every((v,i)=>v===i);const draw=()=>{j.innerHTML='';a.forEach((piece,slot)=>{const d=document.createElement('div');d.className='jp'+(slot===sel?' sel':'');const x=piece%3,y=Math.floor(piece/3);d.style.backgroundImage=`url(${portrait})`;d.style.backgroundPosition=`${x*50}% ${y*50}%`;d.onclick=()=>{if(sel<0)sel=slot;else if(sel===slot)sel=-1;else{[a[sel],a[slot]]=[a[slot],a[sel]];sel=-1;if(ok()){complete();return}}draw()};j.appendChild(d)})};draw()}
 function open(){if(canOpen&&!canOpen()){status.textContent='اقترب من لوحة الباب للتفاعل';status.className='status';return false}const r=getRoom(),t=types[r];modal.classList.add('show');status.textContent=solved[r]?'هذا اللغز محلول مسبقًا':'';status.className=solved[r]?'status solved':'status';title.textContent=`لغز الغرفة ${r+1}`;desc.textContent=t==='jigsaw'?'أعد تركيب الصورة.':t==='pipes'?'اضغط على قطع الأنابيب المجسمة لتدويرها.':t==='valves'?'دوّر عجلات الصمامات المجسمة.':t==='circuit'?'حرّك مفاتيح الطاقة حتى تصل للوضع الصحيح.':t==='pressure'?'اضبط مستويات الضغط الثلاثة.':t==='symbols'?'اضغط الرموز بالتسلسل الصحيح.':t==='frequency'?'اضبط ترددات أجهزة الاستقبال.':t==='keypad'?'أدخل رمز فتح بوابة النقل.':t==='escape'?'نفّذ إجراءات الخروج إلى السطح بالترتيب.':'رتّب المكعبات المجسمة من 1 إلى 9.';({blocks,pipes,valves,circuit,jigsaw,pressure,symbols,frequency,keypad,escape:escapePuzzle}[t])()}
 document.getElementById('use').onclick=open;document.getElementById('close').onclick=()=>{clean3D();modal.classList.remove('show')};return{open,isSolved:r=>solved[r],solve:()=>complete(),close:()=>{clean3D();modal.classList.remove('show')}}
}